export const weatherTheme = {
  "01d": {
    icon: "https://i.ibb.co/fVSRWTLm/sun-icon.png",
    description: "Sun weather icon",
    background: "https://i.ibb.co/7xz1YsLd/clear-sky.gif",
    colour: "#3d89c0ff",
  },
  "01n": {
    icon: "https://i.ibb.co/S8Z8yRm/moon-icon.png",
    description: "Full moon weather icon",
    background: "https://i.ibb.co/0pYHbyLQ/starry-clear-night.gif",
    colour: "#2C3E50",
  },
  "02d": {
    icon: "https://i.ibb.co/nNkpY6b8/sunny-cloud-icon.png",
    description: "Sunny cloud weather icon",
    background: "https://i.ibb.co/0y4pNxp3/sunny-clouds.gif",
    colour: "#738eaa",
  },
  "02n": {
    icon: "https://i.ibb.co/8gZMKK6v/night-cloud-icon.png",
    description: "Cloudy night weather icon",
    background: "https://i.ibb.co/qYfxf4nW/chill-night.gif",
    colour: "#343434",
  },
  "03d": {
    icon: "https://i.ibb.co/v4LCrbk4/cloud-icon.png",
    description: "A cloud weather icon",
    background: "https://i.ibb.co/gMCSVRGk/broken-cloud.gif",
    colour: "#143153",
  },
  "03n": {
    icon: "https://i.ibb.co/v4LCrbk4/cloud-icon.png",
    description: "A cloud weather icon",
    background: "https://i.ibb.co/Nq7JZtq/cloudy-night.gif",
    colour: "#424D50",
  },
  "04d": {
    icon: "https://i.ibb.co/dwk2sj9m/very-cloudy-icon.png",
    description: "Two clouds weather icon",
    background: "https://i.ibb.co/MDpmtvNS/overcast-clouds.gif",
    colour: "#7A7A7A",
  },
  "04n": {
    icon: "https://i.ibb.co/dwk2sj9m/very-cloudy-icon.png",
    description: "Two clouds weather icon",
    background: "https://i.ibb.co/Xfp3gm6H/very-cloudy-night.gif",
    colour: "#1F1729",
  },
  "09d": {
    icon: "https://i.ibb.co/yF6Dcw5c/rain-icon.png",
    description: "Rain cloud weather icon",
    background: "https://i.ibb.co/j9WZrwQV/rain.gif",
    colour: "#1F232B",
  },
  "09n": {
    icon: "https://i.ibb.co/yF6Dcw5c/rain-icon.png",
    description: "Rain cloud weather icon",
    background: "https://i.ibb.co/HRXby4n/rainy-night.gif",
    colour: "#000000",
  },
  "10d": {
    icon: "https://i.ibb.co/7xDJJyGK/rainy-day-icon.png",
    description: "Rain cloud with a sun weather icon",
    background: "https://i.ibb.co/NDzkTbp/rainy-day.gif",
    colour: "#1F232B",
  },
  "10n": {
    icon: "https://i.ibb.co/pjzdc3CZ/rainy-night-icon.png",
    description: "Rain cloud with a full moon weather icon",
    background: "https://i.ibb.co/PGfgybC6/Rainy-street.gif",
    colour: "#000000",
  },
  "11d": {
    icon: "https://i.ibb.co/spfsXSNV/thunderstorm-icon.png",
    description: "Thunderstorm cloud weather icon",
    background: "https://i.ibb.co/JjPXCxh2/thunderstorm.gif",
    colour: "#0F1E26",
  },
  "11n": {
    icon: "https://i.ibb.co/SXtZ8502/thunderstorm-night-icon.png",
    description: "Thunderstorm cloud with a moon weather icon",
    background: "https://i.ibb.co/1fN1SByQ/thunderstorm-night.gif",
    colour: "#030312",
  },
  "13d": {
    icon: "https://i.ibb.co/jZkSjpKt/snow-icon.png",
    description: "A snow cloud icon",
    background: "https://i.ibb.co/5gnXvGdR/snow-day.gif",
    colour: "#383838",
  },
  "13n": {
    icon: "https://i.ibb.co/jZkSjpKt/snow-icon.png",
    description: "A snow cloud icon",
    background: "https://i.ibb.co/tMt1h6pb/snowy-night.gif",
    colour: "#1E2327",
  },
  "50d": {
    icon: "https://i.ibb.co/zTprT45S/mist-icon.png",
    description: "A mist cloud weather icon",
    background: "https://i.ibb.co/Kj4LXh5g/mist.gif",
    colour: "#2F2D2E",
  },
  "50n": {
    icon: "https://i.ibb.co/zTprT45S/mist-icon.png",
    description: "A mist cloud weather icon",
    background: "https://i.ibb.co/Pzm6vVPz/misty-night.gif",
    colour: "#2F2D2E",
  },
};
